blog/urls.py
from django.urls import path, include
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig


app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('blog_list/', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('contacts/', include('catalog.urls', namespace='contacts')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))

]
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models/blog.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    slug = models.CharField(max_length=255, **NULLABLE, unique=True, verbose_name='Ссылка')
    body = models.TextField(verbose_name='Содержимое', **NULLABLE)
    image = models.ImageField(upload_to='blog/', verbose_name='изображение')
    date_creation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    publication_feature = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров', editable=False)

    def __str__(self):
        return f'{self.title}: {self.views_count}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        # ordering = 'title'

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify
from blog.models.blog import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'publication_feature')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'publication_feature',)

    # success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication_feature=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        return self.object

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить блог "{{ object.title }}"? </p>
                    <button type="submit" class="btn button-danger">Подтвердить</button>
                    <a href="{% url 'blog:list' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load static %}

<div class="row text-center">
    <div class="col-md-4">
        <h2>Название: {{object.title}}</h2>
        <p>Slug: {{object.slug}}</p>
        <p>Контент: {{object.body}}</p>
        <p>Признак публикации: {{object.publication_feature}}</p>
        <p>Просмотры: {{ object.views_count }}</p>
        <a href="{% url 'blog:edit' object.pk %}" class="btn btn-success">Редактировать</a>
        <a href="{% url 'blog:list' %}" class="btn btn-secondary">Назад</a>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row text-center">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-primary">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load mediapath_filter %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить блог</a>
</div>
<div class="row text-center">
    {% for object in object_list%}
    <div class="col-md-4">
        <h2>{{object.title}}</h2>
        <img src="{{ object.image|mediapath_filter }}" width="250" height="350" alt="постер">
        <p>{{object.description}}</p>
        <div class="btn-group mb-5">
            <a href="{% url 'blog:view' object.pk %}" class="btn btn-outline-secondary active"
               aria-current="page">Просмотр</a>
            <a href="{% url 'blog:edit' object.pk %}" class="btn btn-success">Редактировать</a>
            <a href="{% url 'blog:delete' object.pk %}" class="btn btn-danger">Удалить</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}