blog/urls.py
from django.urls import path, include
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig


app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('blog_list/', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),

]

catalog/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

import catalog
from catalog import views
from catalog.apps import CatalogConfig
from catalog.views import contacts, HomeListView, HomeCreateView, HomeUpdateView, VersionListView, HomeDeleteView, \
    categories_list

app_name = CatalogConfig.name


urlpatterns = [
    path('contacts/', contacts, name='contacts'),  # http://127.0.0.1:8000/contacts/  Контакты
    path('', cache_page(60)(HomeListView.as_view()), name='home'),  # http://127.0.0.1:8000/ Главная страница
    # path('create/', HomeCreateView.as_view(), name='create_home'),
    # path('update/<int:pk>/', HomeUpdateView.as_view(), name='update_home'),
    path('create/', HomeCreateView.as_view(), name='create_home'),  # http://127.0.0.1:8000/create/
    path('update/<int:pk>/', HomeUpdateView.as_view(), name='update_home'),  # http://127.0.0.1:8000/create/<pk>
    path('delete/<int:pk>/', HomeDeleteView.as_view(), name='delete_home'),  # http://127.0.0.1:8000/delete/<pk>
    path('versions/<int:pk>', VersionListView.as_view(), name='version'),  # http://127.0.0.1:8000/versions/<pk>
    path('categories/', categories_list, name='categories')

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('contacts/', include('catalog.urls', namespace='contacts')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))

]
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, activate_new_user

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('profile/', ProfileView.as_view(template_name='users/user_form.html'), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('activate/<int:pk>/', activate_new_user, name='activate_new_user')

]

catalog/models/category.py
from django.db import models

# Create your models here.
NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='название категории')
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)

catalog/models/products.py
from django.db import models

# Create your models here.
NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='название книги')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    image = models.ImageField(upload_to='products/', verbose_name='изображение')
    category = models.ForeignKey('catalog.Category', on_delete=models.SET_NULL, null=True, verbose_name='Категория')
    purchase_price = models.IntegerField(verbose_name='Цена')
    date_creation = models.DateTimeField(auto_now_add=True)
    date_last_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name} {self.purchase_price}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('name',)

catalog/models/version.py
from django.db import models

from catalog.models.products import Product

# Create your models here.
NULLABLE = {'blank': True, 'null': True}


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='название книги')
    version_number = models.IntegerField(verbose_name='номер версии')
    version_name = models.CharField(max_length=350, verbose_name='название версии')
    description = models.TextField(verbose_name='Описание текущей версии', blank=True, null=True)
    is_active = models.BooleanField(default=True, verbose_name='Активность')

    def __str__(self):
        return f'{self.product} - {self.version_name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

    def clean(self):
        """
        Проверка количества активных версий продукта
        """
        super().clean()
        versions = Version.objects.filter(product=self.product, active_version=True)
        if len(versions) > 1:
            print("Ошибка: 'Активной может быть только одна версия!'")
            print(len(versions))
        else:
            print('Готово!')

catalog/forms.py
from django import forms
from catalog.models.products import Product
from catalog.models.version import Version

banned_words = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар')


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields =('name', 'description', 'image', 'category', 'purchase_price')

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        for word in banned_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('Недопустимые темы в литературе')
        return cleaned_data

    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

catalog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.forms import inlineformset_factory
from catalog.forms import ProductForm, VersionForm
from catalog.models.products import Product
from django.urls import reverse_lazy, reverse

from catalog.models.version import Version
from catalog.services import get_cashed_categories_list


# Create your views here.


def contacts(request):

    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Имя: {name} \nТелефон {phone} \nСообщение {message}')

    return render(request, 'catalog/contacts.html')


def categories_list(request):
    categories = get_cashed_categories_list()
    context = {'object_list': categories, }
    return render(request, 'catalog/categories.html', context)


class HomeListView(ListView):
    model = Product
    template_name = 'catalog/home.html'

# def home(request):
#     products_list = Product.objects.all()
#     context = {'object_list': products_list}
#     return render(request, 'catalog/home.html', context)


class HomeCreateView(CreateView):
    """Класс-контроллер для создания продукта"""
    model = Product  # Модель, с которой он работает
    form_class = ProductForm  # Форма для заполнения
    success_url = reverse_lazy('catalog:home')


class HomeUpdateView(UpdateView):
    """
    Класс-контроллер для редактирования продукта
    """
    model = Product  # Модель, с которой он работает
    form_class = ProductForm  # Форма для заполнения
    success_url = reverse_lazy('catalog:home')

    def get_context_data(self, **kwargs):
        """
        Переопределение метода get_context_data, добавление в контекст формсета
        """
        context_data = super().get_context_data(**kwargs)
        # 1-Родительская модель 2-модель версия 3-модель формы extra-количество новых форм
        VersionFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        """В случае успешного заполнения формы перенаправление на страницу с версиями соответствующего продукта
        """
        return reverse('catalog:version', args=[self.kwargs.get('pk')])


class HomeDeleteView(DeleteView):
    """Класс-контроллер для удаления продукта"""
    model = Product  # Модель, с которой он работает
    # URL адрес, на который происходит перенаправление после успешного удаления записи в блоге
    success_url = reverse_lazy('catalog:home')


class VersionListView(ListView):
    """
    Класс-контроллер для отображения списка активных версии текущего продукта
    """
    model = Version

    def get_queryset(self, *args, **kwargs):
        """
        Переопределение метода get_queryset для возможности отфильтровать активные версии продукта с нужным id
        """
        product_pk = self.kwargs.get('pk')  # получение id продукта
        return Version.objects.filter(is_active=True, product_id=product_pk)

    def get_context_data(self, *args, object_list=None, **kwargs):
        """
        Переопределение метода get_context_data для передачи в шаблон и отображения на странице
         наименования продукта
         """
        product = Product.objects.get(pk=self.kwargs.get('pk'))  # Получение продукта с соответствующим id
        context = super().get_context_data(*args, **kwargs)  # получение контекста
        context['product_name'] = product.name  # добавление в контекст наименования продукта
        context['pk'] = product.pk  # добавление в контекст id продукта
        return context

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
            integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
            crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
            integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
            crossorigin="anonymous"></script>

    <title>Фоксбук</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <img src="https://phonoteka.org/uploads/posts/2023-03/1679759142_phonoteka-org-p-morda-lisi-art-vkontakte-81.jpg"
         width="60" height="50" alt="лисица">
    <h5 class="my-0 mr-md-auto font-weight-normal">Фоксбук</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:categories' %}">Категории</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:create_home' %}">Добавить книгу</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            Фоксбук
            <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y' %}</small>
        </div>
        <div class="col-12 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'blog:list' %}">К Блогам</a></li>
                <li><a class="text-muted" href= "{% url 'catalog:categories' %}">Категории</a></li>
                <li><a class="text-muted" href="{% url 'catalog:create_home' %}">Добавить книгу</a></li>
                {% if user.is_authenticated %}
                    <li><a class="text-muted" href="{% url 'users:logout' %}">Выйти</a></li>
                {% else %}
                    <li><a class="text-muted" href="{% url 'users:login' %}">Войти</a></li>
                    <li><a class="text-muted" href="{% url 'users:register' %}">Регистрация</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="col-6 col-md">
            <h4>Дополнительно</h4>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h4>О нас</h4>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/categories.html
{% extends 'catalog/base.html' %}

{% block content %}
    {% for category in object_list %}
        <h4>Категория: {{ category }}</h4>
    {% endfor %}

{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal">Свяжитесь с нами</h3>
                    <img src="https://thumbs.gfycat.com/LightOilyDromaeosaur-max-1mb.gif" width="290" height="125" alt="лисица">
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load mediapath_tag %}
{% load mediapath_filter %}
{% load static %}

{% block content %}


    <div class="pricing-header px-3 py-3 pt-md-20 pb-md-4 mx-auto text-center">
        <h1 class="display-4"><img
                src="https://phonoteka.org/uploads/posts/2023-03/1679759142_phonoteka-org-p-morda-lisi-art-vkontakte-81.jpg"
                width="90" height="80" alt="лисица">Фоксбук</h1>
        <p class="lead">Фоксбук - это отличный магазин рекомендованных книг к прочтению</p>
    </div>

    <div class="container-sm">
        <div class="row text-center">
            {% for object in object_list %}
                <div class="col-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <img src="{% mediapath_tag object.image %}" width="250" height="350" alt="постер"/>
                            <!-- Tag -->
                            {#                  <img src="{{ object.image|mediapath_filter }}" /> <!-- filter -->#}
                        </div>

                        <div class="card-body">
                            <h2 class="my-0 font-weight-normal">{{ object.name }}</h2>
                        </div>
                        <ul class="container text-center ">
                            <p>Категория: {{ object.category }}</p>
                            <p></p>
                            <p>Описание: {{ object.description|truncatechars:120 }}</p>
                            <p></p>
                            <h5 class="card-title pricing-card-title"> {{ object.purchase_price }} рублей</h5>
                        </ul>
                        {% if user.is_authenticated %}
                            <div class="card-footer">
                                <div class="d-grid gap-2 col-12 mx-auto">
                                    <a href="{% url 'catalog:update_home' object.pk %}" type="button"
                                       class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                                    <a href="{% url 'catalog:delete_home' object.pk %}" type="button"
                                       class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
                                    <a href="{% url 'catalog:version' object.pk %}" type="button"
                                       class="btn btn-lg btn-block btn-outline-primary">К версиям продукта</a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

catalog/templates/catalog/home_confirm_delete.html
{% extends 'catalog/base.html'%}
{% load mediapath_tag %}
{% load mediapath_filter %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Удаление продукта</h1>
    </div>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <form method="post">
            {% csrf_token %}
            Уверены что хотите удалить продукт?
            <button type="submit" class="p-2 btn btn-outline-primary">Удалить продукт</button>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/home_list.html
{% extends 'catalog/base.html' %}
{% load mediapath_tag %}
{% load mediapath_filter %}
{% load static %}

{% block content %}
<div class="container-sm">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <img src="{% mediapath_tag object.image %}" width="250" height="350" alt="постер"/> <!-- Tag -->
{#                  <img src="{{ object.image|mediapath_filter }}" /> <!-- filter -->#}
                </div>
                 <div class="card mb-4 box-shadow">
                 <div class="card-body">
                    <h2 class="my-0 font-weight-normal">{{ object.name }}</h2>
                 </div>
                    <ul class="container text-center ">
                        <p>Категория: {{ object.category }}</p>
                        <p></p>
                        <p>Описание: {{ object.description|slice:':150' }}</p>
                        <p></p>
                        <h5 class="card-title pricing-card-title">{{ object.purchase_price }} рублей</h5>
                    </ul>
                 </div>
                <div class="card-footer">
                    <a href="{% url 'catalog:update_home' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                    <a href="{% url 'catalog:delete_home' object.pk%}" type="button" class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
                    <a href="{% url 'catalog:home' object.pk%}" type="button" class="btn btn-lg btn-block btn-outline-primary">К версиям продукта</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html'%}
{% load mediapath_tag %}
{% load mediapath_filter %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h6 class="display-4">Удаление продукта</h6>
    </div>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <form method="post">
            {% csrf_token %}
            Уверены что хотите удалить продукт?
            <button type="submit" class="p-2 btn btn-outline-primary">Удалить продукт</button>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3">
                <div class="card text-center">
                    <div class="card-header">
                         <figure>
                            <img src="https://yobte.ru/uploads/posts/2019-11/lis-furri-51-foto-17.jpg" width="350" height="250" alt="лисица c книгой">
                            <figcaption><h4>Добавьте книгу</h4></figcaption>
                         </figure>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="buttonbtn btn-outline-success">Сохранить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
         {% if object %}
            <div class="col-3">
                <div class="card text-center">
                    <div class="card-header">
                         <figure>
                            <img src="https://drasler.ru/wp-content/uploads/2019/07/Открытки-с-днем-рождения-лис019.jpg" width="350" height="250" alt="лисица c книгой">
                            <figcaption><h4>Добавьте версию</h4></figcaption>
                         </figure>
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                                <hr>
                            {% endif %}
                        {% endfor %}
                        <button type="submit" class="buttonbtn btn-outline-success">Сохранить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            {% endif %}
            </div>
        </form>
    </div>
{% endblock %}
{#    <div class="container">#}
{#    <div class="row text-center">#}
{#    {% if object_list %}#}
{#        {% for object in object_list %}#}
{#        <div class="col-3">#}
{#            <div class="card mb-4 box-shadow">#}
{#                <div class="card-header">#}
{#                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>#}
{#                </div>#}
{#                <div class="card-body">#}
{#                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">#}
{#                        <li>Описание: {{ object.description }}</li>#}
{#                    </ul>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#        {% endfor %}#}
{#    {% else %}#}
{#        <div class="card mb-4 box-shadow">#}
{#                <div class="card-header">#}
{#                    <h4 class="my-0 font-weight-normal">У товара отсутствуют активные версии</h4>#}
{#                </div>#}
{#         {% endif %}#}
{#        <a href="#" type="button" class="btn btn-lg btn-block btn-outline-primary">Редактировать товар</a>#}
{#        </div>#}

catalog/templates/catalog/version_list.html
{% extends 'catalog/base.html'%}

{% block content %}
     <h1 class="display-4">Список активных версий продукта {{ product_title }}</h1>
<div class="container">
    <div class="row text-center">
    {% if object_list %}
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Описание: {{ object.description }}</li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">У продукта отсутствуют активные версии</h4>
                </div>
    {% endif %}
    <a href="{% url 'catalog:update_home' pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Редактировать продукт</a>
    </div>

</div>
{% endblock %}